export interface Expense {
  id: string;
  type: 'expense';
  date: string; // YYYY-MM-DD
  amount: number;
  currency: 'KRW' | 'SATS';
  btcKrwAtTime: number | null;
  satsEquivalent: number | null;
  category: string;
  paymentMethod: 'cash' | 'card' | 'lightning' | 'onchain' | 'bank';
  cardId: string | null;
  installmentId: string | null;
  installmentMonths: number | null; // 할부 개월 수 (1 = 일시불)
  isInterestFree: boolean | null; // 무이자 여부
  memo: string | null;
  createdAt: string;
  updatedAt: string;
  needsPriceSync: boolean;
  // 자동 생성 기록 관련
  isAutoGenerated?: boolean; // 자동 생성된 기록인지 여부
  linkedLoanId?: string | null; // 연결된 대출 ID
  // 자산 연동 (Phase 5)
  linkedAssetId?: string | null; // 즉시 차감될 자산 (bank/lightning/onchain)
}

export interface Income {
  id: string;
  type: 'income';
  date: string; // YYYY-MM-DD
  amount: number;
  currency: 'KRW' | 'SATS';
  btcKrwAtTime: number | null;
  satsEquivalent: number | null;
  category: string;
  source: string | null;
  memo: string | null;
  createdAt: string;
  updatedAt: string;
  needsPriceSync: boolean;
  // 자산 연동 (Phase 5)
  linkedAssetId?: string | null; // 입금될 자산
}

export interface Transfer {
  id: string;
  type: 'transfer';
  date: string; // YYYY-MM-DD
  amount: number;
  currency: 'KRW' | 'SATS';
  fromAssetId: string;
  toAssetId: string | null;
  toCardId: string | null;
  memo: string | null;
  createdAt: string;
  updatedAt: string;
}

export type LedgerRecord = Expense | Income | Transfer;

export function isExpense(record: LedgerRecord): record is Expense {
  return record.type === 'expense';
}

export function isIncome(record: LedgerRecord): record is Income {
  return record.type === 'income';
}

export function isTransfer(record: LedgerRecord): record is Transfer {
  return record.type === 'transfer';
}
